# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 02:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='intoroduction',
            new_name='introduction',
        ),
    ]
